import Head from "next/head";
import Image from "next/image";
import SlideShow from "../components/SlideShow";
import Category from "../components/Category";
import ListApplication from "../components/ListApplication";
import ListCompany from "../components/ListCompany";
import Quote from "../components/Quote";

const Home = ({
  data_company,
  data_slides,
  data_categories,
  data_applications,
  data_navbar,
}) => {
  return (
    <div className="home">
      <Head>
        <title>
          Airius | Destratification Fans | Air Purification | LED Lighting |
          Electrical
        </title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      {/* <div className="header-top-img">
        <Image
          src={`/img/xc.jpg`}
          alt="logo Airius"
          layout="fill"
          data-testid="close-icon"
          objectFit="contain"
        />
      </div> */}
      <SlideShow {...data_slides} />
      <Category {...data_categories} />
      <h1 className="home-title">SOLUTIONS FOR EVERY APPLICATION</h1>
      <ListApplication {...data_applications} />
      <ListCompany {...data_company} />
      <Quote />
    </div>
  );
};

export async function getStaticProps({ params }) {
  const navbar = await fetch(
    `https://hidden-fortress-12666.herokuapp.com/api/navbar`
  );
  const slides = await fetch(
    `https://hidden-fortress-12666.herokuapp.com/api/slides`
  );
  const categories = await fetch(
    `https://hidden-fortress-12666.herokuapp.com/api/categories`
  );
  const applications = await fetch(
    `https://hidden-fortress-12666.herokuapp.com/api/applications`
  );
  const company = await fetch(
    `https://hidden-fortress-12666.herokuapp.com/api/company`
  );
  const data_slides = Array(await slides.json());
  const data_navbar = Array(await navbar.json());
  const data_categories = Array(await categories.json());
  const data_applications = Array(await applications.json());
  const data_company = Array(await company.json());

  return {
    props: {
      data_slides,
      data_navbar,
      data_categories,
      data_applications,
      data_company,
    },
  };
}

export default Home;
